production:
  google_mail_host: 'gmail.com'
  google_picasa_base_url: 'https://picasaweb.google.com/data/feed/api/user/'

development:
  google_mail_host: 'gmail.com'
  google_picasa_base_url: 'https://picasaweb.google.com/data/feed/api/user/'

test:
  google_mail_host: 'gmail.com'
  google_picasa_base_url: 'https://picasaweb.google.com/data/feed/api/user/'